### PR TITLE
Add the ability to manage the user and group for nrpe

### PR DESCRIPTION
**Pull request by coreone**
#### Pull Request (PR) description
Add the ability to manage the user and group for nrpe.  By default, this is turned off, but can easily be turned on if the user or group were not added automatically by the package.

### CODE REVIEW

**Comment by coreone** [comment]
The failure is being caused because there is no Puppet 7 apt repo for Debian 8 (Jessie)

**Comment by coreone** [comment]
A rebase fixed the checks for this. Is there anything else needed here before this can be merged?

**Comment by coreone** [comment]
Rebased to resolve conflicts. Looks like OracleLinux 7 issues are what's keeping the tests from passing.

**Comment by coreone** [comment]
@bastelfreak anything else needed here? The error seems to be coming from a package not being available on OL7.

**Comment by bastelfreak** [comment]
thanks for the code!

**Pull request merged**
